// Builds the Python source that runs one "function call" test case.
//
// In 'function' input mode a test case's input is not stdin — it's a call expression the
// teacher wrote, e.g. `rectangle_area(4, 5)`. The student only writes the function:
//
//     def rectangle_area(width, height):
//         return width * height
//
// so we append a harness that evaluates the expression and prints the result.
//
// A student may legitimately either RETURN the answer or PRINT it, and both must pass, so
// stdout is captured around the call:
//   - the call returned something  -> that value is the answer (anything it printed is
//                                     ignored, otherwise a function that both prints and
//                                     returns would emit two lines)
//   - the call returned None       -> whatever the call printed is the answer
//
// Only output produced BY THE CALL counts: the buffer is marked first, so top-level prints
// in the student's file (module-level scratch output) can't leak into the comparison.
//
// Lives in api/ so there is exactly one copy: api/judge.ts imports it as './_pyHarness.js'
// (Node's native ESM loader needs the extension — see api/_supabaseAdmin.ts) and the
// browser-side Pyodide runner imports it through Vite as '../api/_pyHarness'.
// Files prefixed with _ are not routes.

// Kept to a single line so the student's code still starts on line 2 and traceback line
// numbers stay almost unchanged.
const PROLOGUE =
  'import io as __ue_io, sys as __ue_sys; __ue_buf = __ue_io.StringIO(); __ue_out = __ue_sys.stdout; __ue_sys.stdout = __ue_buf';

export const buildFunctionCallSource = (studentCode: string, callExpression: string): string => {
  const expr = String(callExpression || '').trim();
  return [
    PROLOGUE,
    studentCode,
    '',
    '# --- auto-generated by UniExam to run this test case (not the student\'s code) ---',
    '__ue_mark = __ue_buf.tell()',
    'try:',
    '    __ue_ret = (',
    expr,
    '    )',
    'finally:',
    '    __ue_sys.stdout = __ue_out',
    'if __ue_ret is not None:',
    '    print(__ue_ret)',
    'else:',
    '    __ue_buf.seek(__ue_mark)',
    '    __ue_sys.stdout.write(__ue_buf.read())',
    '',
  ].join('\n');
};

// A call expression is required in 'function' mode — an empty one would compile into a
// syntax error that reads as if the student broke something.
export const describeEmptyCall = (index: number) =>
  `Test Case ${index + 1}: this question is set to "function call" mode but the test case has no call expression (e.g. rectangle_area(4, 5)). Ask your instructor to fix the question.`;
