// Builds the Python source that runs one "function call" test case.
//
// In 'function' input mode a test case's input is not stdin — it's a call expression the
// teacher wrote, e.g. `rectangle_area(4, 5)`. The student only writes the function:
//
//     def rectangle_area(width, height):
//         return width * height
//
// so we append a harness that evaluates the expression and prints the result.
//
// A student may legitimately either RETURN the answer or PRINT it, and both must pass, so
// stdout is captured around the call:
//   - the call returned something  -> that value is the answer (anything it printed is
//                                     ignored, otherwise a function that both prints and
//                                     returns would emit two lines)
//   - the call returned None       -> whatever the call printed is the answer
//
// Only output produced BY THE CALL counts: the buffer is marked first, so top-level prints
// in the student's file (module-level scratch output) can't leak into the comparison.
//
// Lives in api/ so there is exactly one copy: api/judge.ts imports it as './_pyHarness.js'
// (Node's native ESM loader needs the extension — see api/_supabaseAdmin.ts) and the
// browser-side Pyodide runner imports it through Vite as '../api/_pyHarness'.
// Files prefixed with _ are not routes.

// Kept to a single line so the student's code still starts on line 2 and traceback line
// numbers stay almost unchanged.
const PROLOGUE =
  'import io as __ue_io, sys as __ue_sys; __ue_buf = __ue_io.StringIO(); __ue_out = __ue_sys.stdout; __ue_sys.stdout = __ue_buf';

export const buildFunctionCallSource = (studentCode: string, callExpression: string): string => {
  const expr = String(callExpression || '').trim();
  return [
    PROLOGUE,
    studentCode,
    '',
    '# --- auto-generated by UniExam to run this test case (not the student\'s code) ---',
    '__ue_mark = __ue_buf.tell()',
    'try:',
    '    __ue_ret = (',
    expr,
    '    )',
    'finally:',
    '    __ue_sys.stdout = __ue_out',
    'if __ue_ret is not None:',
    '    print(__ue_ret)',
    'else:',
    '    __ue_buf.seek(__ue_mark)',
    '    __ue_sys.stdout.write(__ue_buf.read())',
    '',
  ].join('\n');
};

// A call expression is required in 'function' mode — an empty one would compile into a
// syntax error that reads as if the student broke something.
export const describeEmptyCall = (index: number) =>
  `Test Case ${index + 1}: this question is set to "function call" mode but the test case has no call expression (e.g. rectangle_area(4, 5)). Ask your instructor to fix the question.`;

// ==========================================
// ALL TEST CASES IN ONE SUBMISSION
// ==========================================
// Sphere Engine bills per submission, and the account has a fixed pool of them. Sending
// each test case separately spent four on every press of "ส่งคำตอบ": a class of 118
// sitting three code questions would need 1,416, against 471 left. Running every case
// inside one program costs one, which is what makes the exam possible at all.
//
// The cases are kept apart from each other: stdout is captured per case and exceptions are
// caught per case, so one failing case still reports as one failing case rather than
// taking the rest with it. What they do share is the process — a case that loops forever
// takes the whole submission's time limit with it, and in 'stdin' mode they also share
// whatever the student's module-level code left behind in globals.
//
// Markers delimit each case's answer in stdout. They are deliberately unlikely strings:
// a student printing one would misreport their own result, and nothing else about the
// format can be made safe against that.
export const BATCH_BEGIN = '__UE_CASE_BEGIN_7f3a__';
export const BATCH_END = '__UE_CASE_END_7f3a__';
export const BATCH_ERROR = '__UE_CASE_ERROR_7f3a__';
export const BATCH_SYNTAX_ERROR = '__UE_SYNTAX_ERROR_7f3a__';

// JSON string syntax is a subset of Python's, escapes included, so this is a safe way to
// hand arbitrary text to the generated program.
const pyString = (value: string) => JSON.stringify(String(value ?? ''));

const BATCH_PROLOGUE = [
  'import io as __ue_io, sys as __ue_sys, builtins as __ue_builtins, traceback as __ue_tb',
  '__ue_real = __ue_sys.stdout',
  '__ue_results = []',
].join('\n');

const BATCH_EPILOGUE = [
  '__ue_sys.stdout = __ue_real',
  'for __ue_i in range(len(__ue_results)):',
  '    __ue_ret, __ue_cap, __ue_e = __ue_results[__ue_i]',
  `    print(${pyString(BATCH_BEGIN)} + str(__ue_i))`,
  '    if __ue_e is not None:',
  `        print(${pyString(BATCH_ERROR)})`,
  '        print(__ue_e)',
  '    elif __ue_ret is not None:',
  '        print(__ue_ret)',
  '    else:',
  '        __ue_sys.stdout.write(__ue_cap)',
  '        if not __ue_cap.endswith("\\n"):',
  '            print("")',
  `    print(${pyString(BATCH_END)} + str(__ue_i))`,
  '',
].join('\n');

// 'function' mode: the student's code is compiled as part of the program, so a syntax
// error in it is a real compilation error, exactly as before. Its module-level output is
// captured and discarded so scratch prints can't be mistaken for an answer.
export const buildFunctionBatchSource = (studentCode: string, callExpressions: string[]): string => {
  const cases = callExpressions.map((expr, i) =>
    [
      `# --- test case ${i + 1} (auto-generated by UniExam, not the student's code) ---`,
      '__ue_buf = __ue_io.StringIO()',
      '__ue_sys.stdout = __ue_buf',
      'try:',
      '    __ue_ret = (',
      String(expr || '').trim(),
      '    )',
      '    __ue_err = None',
      'except BaseException:',
      '    __ue_ret = None',
      '    __ue_err = __ue_tb.format_exc()',
      'finally:',
      '    __ue_sys.stdout = __ue_real',
      '__ue_results.append((__ue_ret, __ue_buf.getvalue(), __ue_err))',
    ].join('\n')
  );

  return [
    BATCH_PROLOGUE,
    '__ue_scratch = __ue_io.StringIO()',
    '__ue_sys.stdout = __ue_scratch',
    studentCode,
    '__ue_sys.stdout = __ue_real',
    '',
    ...cases,
    '',
    BATCH_EPILOGUE,
  ].join('\n');
};

// 'stdin' mode: the program is run once per case with that case's input, so the student's
// code is held as a string and compiled rather than inlined — which means a syntax error
// surfaces here instead of as a compilation error, and is announced with its own marker so
// the judge can still report it as one.
export const buildStdinBatchSource = (studentCode: string, inputs: string[]): string =>
  [
    BATCH_PROLOGUE,
    `__ue_src = ${pyString(studentCode)}`,
    'try:',
    "    __ue_code = compile(__ue_src, 'prog.py', 'exec')",
    'except SyntaxError:',
    `    print(${pyString(BATCH_SYNTAX_ERROR)})`,
    '    print(__ue_tb.format_exc())',
    '    __ue_sys.exit(0)',
    `__ue_inputs = [${inputs.map(pyString).join(', ')}]`,
    'for __ue_data in __ue_inputs:',
    '    __ue_buf = __ue_io.StringIO()',
    '    __ue_lines = iter(__ue_data.split("\\n"))',
    '    def __ue_input(prompt="", __ue_lines=__ue_lines):',
    '        try:',
    '            return next(__ue_lines)',
    '        except StopIteration:',
    '            return ""',
    '    __ue_builtins.input = __ue_input',
    '    __ue_sys.stdin = __ue_io.StringIO(__ue_data)',
    '    __ue_sys.stdout = __ue_buf',
    '    __ue_err = None',
    '    try:',
    "        exec(__ue_code, {'__name__': '__main__'})",
    '    except BaseException:',
    '        __ue_err = __ue_tb.format_exc()',
    '    finally:',
    '        __ue_sys.stdout = __ue_real',
    '    __ue_results.append((None, __ue_buf.getvalue(), __ue_err))',
    '',
    BATCH_EPILOGUE,
  ].join('\n');

export interface BatchCaseResult {
  answer: string;
  error?: string;
}

// Pulls each case's answer back out of stdout. A case whose markers are missing — the
// program died partway, or printed something that broke the framing — comes back as an
// error rather than as an empty answer that would quietly read as a wrong one.
export const parseBatchOutput = (stdout: string, count: number): BatchCaseResult[] => {
  const text = String(stdout || '');
  return Array.from({ length: count }, (_, i) => {
    const start = text.indexOf(`${BATCH_BEGIN}${i}\n`);
    const end = text.indexOf(`${BATCH_END}${i}`, start);
    if (start === -1 || end === -1) {
      return { answer: '', error: 'ไม่พบผลลัพธ์ของ test case นี้ (โปรแกรมอาจหยุดกลางคัน)' };
    }
    const body = text.slice(start + `${BATCH_BEGIN}${i}\n`.length, end);
    if (body.startsWith(`${BATCH_ERROR}\n`)) {
      return { answer: '', error: body.slice(`${BATCH_ERROR}\n`.length).trim() };
    }
    return { answer: body };
  });
};
